### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by jrock2004** [DingoEatingFuzz/ember-test-audit#1]
How do I use this? Do I have to run tests and then while they are running, run this?

**Comment by jrock2004** [comment]
I have tried 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/655716/66925810-fdc63a80-effa-11e9-96af-ee9af85eb3d6.png">

**Comment by backspace** [comment]
It runs the tests itself. Try `npx ember-test-audit` alone? The arguments are `npx ember-test-audit number-of-repetitions filter`.

**Comment by jrock2004** [comment]
That worked, thanks
